// Stored track centrelines.
//
// The 3D viewer used to build the road around the driven line, which put the
// reference lap exactly mid-track by construction — you could never see
// yourself take a kerb or run wide. iRacing's GPS matches the real world to
// within 3 m (checked at Spa against a surveyed reference), so where a real
// centreline is known the road is laid around *that* instead, and the driven
// line falls wherever it actually was.
//
// Files are generated by scripts/build-track.mjs from OpenStreetMap and keyed
// by iRacing's TrackID, which identifies the layout as well as the venue.
// Anything not covered falls back to the driven line as before.

export interface StoredTrack {
  trackId: number
  trackName: string
  displayName: string
  config: string
  source: string
  /** Median width in metres — the fallback when no per-point widths are stored */
  width: number
  /**
   * Distance in metres from the centreline to each edge, per centreline point.
   * A real circuit is neither a constant width nor symmetric: Spa runs from 7.4
   * to 16.6 m and is up to 1.4 m wider on one side than the other.
   */
  edgeLeft?: number[]
  edgeRight?: number[]
  /** Metres between the driven reference lap and this centreline, from the fit */
  fitResidual?: number
  /** [lat, lon] pairs, evenly spaced, ordered around the lap */
  centreline: [number, number][]
}

// Bundled at build time: a handful of small JSON files, no network at runtime
const FILES = import.meta.glob<StoredTrack>('../data/tracks/*.json', {
  eager: true,
  import: 'default',
})

const BY_ID = new Map<number, StoredTrack>()
for (const mod of Object.values(FILES)) {
  const t = mod as StoredTrack
  if (t?.trackId && t.centreline?.length) BY_ID.set(t.trackId, t)
}

export function storedTrack(trackId: number | null | undefined): StoredTrack | null {
  return trackId == null ? null : BY_ID.get(trackId) ?? null
}

export const storedTrackCount = BY_ID.size
